services:
  # --- 1. PostgreSQL Database ---
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: bps
      POSTGRES_PASSWORD: lol
      POSTGRES_DB: bps_db
    ports:
      - "5432:5432"
    volumes:
      - bps_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 2s
      timeout: 2s
      retries: 30

  # --- 2. MinIO (Local S3) ---
  minio:
    image: minio/minio
    container_name: local_s3
    ports:
      - "9000:9000"  # API Port
      - "9001:9001"  # Console Port
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "password"
    volumes:
      - ./minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 2s   # Reduced interval for faster local dev
      timeout: 1s
      retries: 15

  # --- 3. MinIO Setup (Creates Bucket) ---
  minio-setup:
    image: minio/mc
    container_name: local_s3_setup
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      until (mc alias set local http://minio:9000 admin password); do echo '...waiting for MinIO...'; sleep 1; done;
      mc mb local/my-app-bucket || echo 'Bucket already exists'; 
      mc anonymous set public local/my-app-bucket;
      exit 0;
      "

  # --- 4. HTTP Backend Service ---
  http:
    build:
      context: .
      dockerfile: apps/http/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
      minio-setup:
        # Wait for the bucket to be created before starting the app
        condition: service_completed_successfully 
    ports:
      - "3000:3000"
    volumes:
      - .:/repo
      - /repo/node_modules
      - /repo/apps/http/node_modules
    environment:
      NODE_ENV: development
      CI: "true"
      DATABASE_URL: postgres://bps:lol@postgres:5432/bps_db
      UV_THREADPOOL_SIZE: 8

      # --- S3 Config (Internal Docker Network) ---
      AWS_ACCESS_KEY_ID: "admin"
      AWS_SECRET_ACCESS_KEY: "password"
      AWS_BUCKET_NAME: "my-app-bucket"
      AWS_REGION: "us-east-1"
      # Crucial: Inside Docker, we talk to the container name 'minio', not localhost
      AWS_ENDPOINT: "http://minio:9000"
    
    command: sh -lc "pnpm install && pnpm -C packages/db exec prisma generate && pnpm -C apps/http run dev"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:3000/api/v1/healthz >/dev/null 2>&1 || exit 1"]
      interval: 2s
      timeout: 2s
      retries: 60

  # --- 5. Migration Service (Optional Tool) ---
  migrate:
    build:
      context: .
      dockerfile: apps/http/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/repo
      - /repo/node_modules
    working_dir: /repo/packages/db
    environment:
      CI: "true"
      DATABASE_URL: postgres://bps:lol@postgres:5432/bps_db
    command: sh -lc "pnpm install && npx prisma generate && npx prisma migrate reset --force && npx prisma migrate dev --name dev"
    profiles: ["tools"]

volumes:
  bps_pgdata: