version: '3.8'

services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: local_s3
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "password123"
    command: server /data --console-address ":9001"
    volumes:
      - ./minio_data:/data 

  createbuckets:
    image: quay.io/minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc config host add myminio http://minio:9000 admin password123;
      /usr/bin/mc mb myminio/avatars;
      /usr/bin/mc anonymous set public myminio/avatars;
      exit 0;
      "