import uuid

from django.contrib import admin
from django.apps import apps
from django.conf import settings
from django.utils import timezone
from django.utils.html import format_html


def _image_preview(key):
    """Generate an HTML image preview tag for an S3 key."""
    if not key:
        return '(no image)'
    url = f'{settings.S3_ENDPOINT}/{settings.S3_BUCKET_NAME}/{key}'
    return format_html(
        '<img src="{}" style="max-height:200px; max-width:200px; border:1px solid #ccc; border-radius:4px;" />',
        url,
    )


# models.py is regenerated by inspectdb on every startup. During that step the
# file is temporarily empty, so these imports can fail. Wrap in try/except so
# Django's admin autodiscovery doesn't crash the management command pipeline.
class AutoUuidAdmin(admin.ModelAdmin):
    """ModelAdmin that auto-generates a UUID for TextField primary keys."""

    def get_exclude(self, request, obj=None):
        exclude = list(super().get_exclude(request, obj) or [])
        if obj is None:
            exclude.append('id')
        return exclude

    def get_readonly_fields(self, request, obj=None):
        readonly = list(super().get_readonly_fields(request, obj))
        if obj is not None:
            readonly.append('id')
        return readonly

    def save_model(self, request, obj, form, change):
        if not change and not obj.pk:
            obj.pk = str(uuid.uuid4())
        super().save_model(request, obj, form, change)


try:
    from core.models import Avatar, Element, Map, Mapelementplacement, Space, Spaceelementplacement
    from core.forms import get_avatar_form, get_element_form, get_map_form

    class AvatarAdmin(admin.ModelAdmin):
        form = get_avatar_form(Avatar)
        list_display = ('name', 'image_key', 'user', 'created_at')
        readonly_fields = ('id', 'created_at', 'updated_at', 'image_preview')
        search_fields = ('name',)

        def image_preview(self, obj):
            return _image_preview(obj.image_key)

        image_preview.short_description = 'Current Image'

    class ElementAdmin(admin.ModelAdmin):
        form = get_element_form(Element)
        list_display = ('name', 'width', 'height', 'static', 'image_key', 'created_at')
        readonly_fields = ('id', 'created_at', 'updated_at', 'image_preview')
        search_fields = ('name',)
        list_filter = ('static',)

        def image_preview(self, obj):
            return _image_preview(obj.image_key)

        image_preview.short_description = 'Current Image'

    class MapAdmin(admin.ModelAdmin):
        form = get_map_form(Map)
        list_display = ('name', 'width', 'height', 'thumbnail_key', 'created_at')
        readonly_fields = ('id', 'created_at', 'updated_at', 'thumbnail_preview')
        search_fields = ('name',)

        def thumbnail_preview(self, obj):
            return _image_preview(obj.thumbnail_key)

        thumbnail_preview.short_description = 'Current Thumbnail'

    admin.site.register(Avatar, AvatarAdmin)
    admin.site.register(Element, ElementAdmin)
    admin.site.register(Map, MapAdmin)
    class SpaceAdmin(AutoUuidAdmin):
        readonly_fields = ('created_at', 'updated_at')

        def get_exclude(self, request, obj=None):
            exclude = super().get_exclude(request, obj)
            if obj is None:
                exclude.extend(['created_at', 'updated_at', 'deleted_at'])
            return exclude

        def save_model(self, request, obj, form, change):
            now = timezone.now()
            if not change:
                obj.created_at = now
            obj.updated_at = now
            super().save_model(request, obj, form, change)

    admin.site.register(Mapelementplacement, AutoUuidAdmin)
    admin.site.register(Space, SpaceAdmin)
    admin.site.register(Spaceelementplacement, AutoUuidAdmin)

except ImportError:
    # Models not yet generated (inspectdb hasn't finished writing models.py).
    # Custom admin classes will be available on the next management command in
    # the startup chain (makemigrations, migrate, runserver).
    pass


# Auto-register any models that weren't manually registered above.
for model in apps.get_app_config('core').get_models():
    try:
        admin.site.register(model)
    except admin.sites.AlreadyRegistered:
        pass
